# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

import unittest

import stardust_core_sdk
from stardust_core_sdk.model.sd_player_withdraw_object import SDPlayerWithdrawObject
from stardust_core_sdk import configuration


class TestSDPlayerWithdrawObject(unittest.TestCase):
    """SDPlayerWithdrawObject unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
