# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stardust_core_sdk import schemas  # noqa: F401


class SDOrderCancelRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "gameId",
            "orderId",
        }
        
        class properties:
            
            
            class gameId(
                schemas.IntSchema
            ):
                pass
            
            
            class orderId(
                schemas.IntSchema
            ):
                pass
            fromPlayerId = schemas.StrSchema
            __annotations__ = {
                "gameId": gameId,
                "orderId": orderId,
                "fromPlayerId": fromPlayerId,
            }
    
    gameId: MetaOapg.properties.gameId
    orderId: MetaOapg.properties.orderId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gameId"]) -> MetaOapg.properties.gameId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderId"]) -> MetaOapg.properties.orderId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fromPlayerId"]) -> MetaOapg.properties.fromPlayerId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["gameId", "orderId", "fromPlayerId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gameId"]) -> MetaOapg.properties.gameId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderId"]) -> MetaOapg.properties.orderId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fromPlayerId"]) -> typing.Union[MetaOapg.properties.fromPlayerId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["gameId", "orderId", "fromPlayerId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        gameId: typing.Union[MetaOapg.properties.gameId, decimal.Decimal, int, ],
        orderId: typing.Union[MetaOapg.properties.orderId, decimal.Decimal, int, ],
        fromPlayerId: typing.Union[MetaOapg.properties.fromPlayerId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SDOrderCancelRequest':
        return super().__new__(
            cls,
            *_args,
            gameId=gameId,
            orderId=orderId,
            fromPlayerId=fromPlayerId,
            _configuration=_configuration,
            **kwargs,
        )
