# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stardust_core_sdk import schemas  # noqa: F401


class SDPlayerCreateRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "userData",
            "uniqueId",
        }
        
        class properties:
            uniqueId = schemas.StrSchema
            userData = schemas.DictSchema
            image = schemas.StrSchema
            __annotations__ = {
                "uniqueId": uniqueId,
                "userData": userData,
                "image": image,
            }
    
    userData: MetaOapg.properties.userData
    uniqueId: MetaOapg.properties.uniqueId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uniqueId"]) -> MetaOapg.properties.uniqueId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userData"]) -> MetaOapg.properties.userData: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["image"]) -> MetaOapg.properties.image: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["uniqueId", "userData", "image", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uniqueId"]) -> MetaOapg.properties.uniqueId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userData"]) -> MetaOapg.properties.userData: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["image"]) -> typing.Union[MetaOapg.properties.image, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["uniqueId", "userData", "image", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        userData: typing.Union[MetaOapg.properties.userData, dict, frozendict.frozendict, ],
        uniqueId: typing.Union[MetaOapg.properties.uniqueId, str, ],
        image: typing.Union[MetaOapg.properties.image, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SDPlayerCreateRequest':
        return super().__new__(
            cls,
            *_args,
            userData=userData,
            uniqueId=uniqueId,
            image=image,
            _configuration=_configuration,
            **kwargs,
        )
