# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stardust_core_sdk import schemas  # noqa: F401


class SDTokenTransferRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "tokenObjects",
            "toPlayerId",
            "fromPlayerId",
        }
        
        class properties:
            fromPlayerId = schemas.StrSchema
            toPlayerId = schemas.StrSchema
            
            
            class tokenObjects(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.DictSchema
                    ):
                    
                    
                        class MetaOapg:
                            required = {
                                "amount",
                                "tokenId",
                            }
                            
                            class properties:
                                
                                
                                class tokenId(
                                    schemas.IntSchema
                                ):
                                    pass
                                amount = schemas.StrSchema
                                __annotations__ = {
                                    "tokenId": tokenId,
                                    "amount": amount,
                                }
                        
                        amount: MetaOapg.properties.amount
                        tokenId: MetaOapg.properties.tokenId
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["tokenId"]) -> MetaOapg.properties.tokenId: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
                        
                        @typing.overload
                        def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                        
                        def __getitem__(self, name: typing.Union[typing_extensions.Literal["tokenId", "amount", ], str]):
                            # dict_instance[name] accessor
                            return super().__getitem__(name)
                        
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["tokenId"]) -> MetaOapg.properties.tokenId: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                        
                        def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tokenId", "amount", ], str]):
                            return super().get_item_oapg(name)
                        
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, ],
                            amount: typing.Union[MetaOapg.properties.amount, str, ],
                            tokenId: typing.Union[MetaOapg.properties.tokenId, decimal.Decimal, int, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'items':
                            return super().__new__(
                                cls,
                                *_args,
                                amount=amount,
                                tokenId=tokenId,
                                _configuration=_configuration,
                                **kwargs,
                            )
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]], typing.List[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenObjects':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            __annotations__ = {
                "fromPlayerId": fromPlayerId,
                "toPlayerId": toPlayerId,
                "tokenObjects": tokenObjects,
            }
    
    tokenObjects: MetaOapg.properties.tokenObjects
    toPlayerId: MetaOapg.properties.toPlayerId
    fromPlayerId: MetaOapg.properties.fromPlayerId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fromPlayerId"]) -> MetaOapg.properties.fromPlayerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["toPlayerId"]) -> MetaOapg.properties.toPlayerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenObjects"]) -> MetaOapg.properties.tokenObjects: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["fromPlayerId", "toPlayerId", "tokenObjects", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fromPlayerId"]) -> MetaOapg.properties.fromPlayerId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["toPlayerId"]) -> MetaOapg.properties.toPlayerId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenObjects"]) -> MetaOapg.properties.tokenObjects: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["fromPlayerId", "toPlayerId", "tokenObjects", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        tokenObjects: typing.Union[MetaOapg.properties.tokenObjects, list, tuple, ],
        toPlayerId: typing.Union[MetaOapg.properties.toPlayerId, str, ],
        fromPlayerId: typing.Union[MetaOapg.properties.fromPlayerId, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SDTokenTransferRequest':
        return super().__new__(
            cls,
            *_args,
            tokenObjects=tokenObjects,
            toPlayerId=toPlayerId,
            fromPlayerId=fromPlayerId,
            _configuration=_configuration,
            **kwargs,
        )
