# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stardust_core_sdk import schemas  # noqa: F401


class SDTemplateCreateBulk(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "image",
            "name",
        }
        
        class properties:
            name = schemas.StrSchema
            image = schemas.StrSchema
            cap = schemas.StrSchema
            
            
            class contractType(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ERC721": "ERC721",
                    }
                
                @schemas.classproperty
                def ERC721(cls):
                    return cls("ERC721")
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "FT": "FT",
                        "NFT": "NFT",
                    }
                
                @schemas.classproperty
                def FT(cls):
                    return cls("FT")
                
                @schemas.classproperty
                def NFT(cls):
                    return cls("NFT")
            description = schemas.StrSchema
            activeListing = schemas.BoolSchema
            ownerAddress = schemas.StrSchema
            
            
            class props(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    class properties:
                        immutable = schemas.DictSchema
                        mutable = schemas.DictSchema
                        mutable = schemas.DictSchema
                        __annotations__ = {
                            "immutable": immutable,
                            "mutable": mutable,
                            "$mutable": mutable,
                        }
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["immutable"]) -> MetaOapg.properties.immutable: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["mutable"]) -> MetaOapg.properties.mutable: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["$mutable"]) -> MetaOapg.properties.mutable: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["immutable", "mutable", "$mutable", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["immutable"]) -> typing.Union[MetaOapg.properties.immutable, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["mutable"]) -> typing.Union[MetaOapg.properties.mutable, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["$mutable"]) -> typing.Union[MetaOapg.properties.mutable, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["immutable", "mutable", "$mutable", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    immutable: typing.Union[MetaOapg.properties.immutable, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
                    mutable: typing.Union[MetaOapg.properties.mutable, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'props':
                    return super().__new__(
                        cls,
                        *_args,
                        immutable=immutable,
                        mutable=mutable,
                        _configuration=_configuration,
                        **kwargs,
                    )
            publicContractMetadata = schemas.DictSchema
            publicTokenMetadata = schemas.DictSchema
            __annotations__ = {
                "name": name,
                "image": image,
                "cap": cap,
                "contractType": contractType,
                "type": type,
                "description": description,
                "activeListing": activeListing,
                "ownerAddress": ownerAddress,
                "props": props,
                "publicContractMetadata": publicContractMetadata,
                "publicTokenMetadata": publicTokenMetadata,
            }
    
    image: MetaOapg.properties.image
    name: MetaOapg.properties.name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["image"]) -> MetaOapg.properties.image: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cap"]) -> MetaOapg.properties.cap: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contractType"]) -> MetaOapg.properties.contractType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activeListing"]) -> MetaOapg.properties.activeListing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ownerAddress"]) -> MetaOapg.properties.ownerAddress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["props"]) -> MetaOapg.properties.props: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["publicContractMetadata"]) -> MetaOapg.properties.publicContractMetadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["publicTokenMetadata"]) -> MetaOapg.properties.publicTokenMetadata: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "image", "cap", "contractType", "type", "description", "activeListing", "ownerAddress", "props", "publicContractMetadata", "publicTokenMetadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["image"]) -> MetaOapg.properties.image: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cap"]) -> typing.Union[MetaOapg.properties.cap, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contractType"]) -> typing.Union[MetaOapg.properties.contractType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activeListing"]) -> typing.Union[MetaOapg.properties.activeListing, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ownerAddress"]) -> typing.Union[MetaOapg.properties.ownerAddress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["props"]) -> typing.Union[MetaOapg.properties.props, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["publicContractMetadata"]) -> typing.Union[MetaOapg.properties.publicContractMetadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["publicTokenMetadata"]) -> typing.Union[MetaOapg.properties.publicTokenMetadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "image", "cap", "contractType", "type", "description", "activeListing", "ownerAddress", "props", "publicContractMetadata", "publicTokenMetadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        image: typing.Union[MetaOapg.properties.image, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        cap: typing.Union[MetaOapg.properties.cap, str, schemas.Unset] = schemas.unset,
        contractType: typing.Union[MetaOapg.properties.contractType, str, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        activeListing: typing.Union[MetaOapg.properties.activeListing, bool, schemas.Unset] = schemas.unset,
        ownerAddress: typing.Union[MetaOapg.properties.ownerAddress, str, schemas.Unset] = schemas.unset,
        props: typing.Union[MetaOapg.properties.props, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        publicContractMetadata: typing.Union[MetaOapg.properties.publicContractMetadata, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        publicTokenMetadata: typing.Union[MetaOapg.properties.publicTokenMetadata, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SDTemplateCreateBulk':
        return super().__new__(
            cls,
            *_args,
            image=image,
            name=name,
            cap=cap,
            contractType=contractType,
            type=type,
            description=description,
            activeListing=activeListing,
            ownerAddress=ownerAddress,
            props=props,
            publicContractMetadata=publicContractMetadata,
            publicTokenMetadata=publicTokenMetadata,
            _configuration=_configuration,
            **kwargs,
        )
