# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stardust_core_sdk import schemas  # noqa: F401


class SDTokenGetResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    token data
    """


    class MetaOapg:
        required = {
            "gameId",
            "flags",
            "id",
            "templateId",
            "props",
        }
        
        class properties:
            
            
            class gameId(
                schemas.IntSchema
            ):
                pass
            
            
            class templateId(
                schemas.IntSchema
            ):
                pass
            
            
            class id(
                schemas.IntSchema
            ):
                pass
            
            
            class flags(
                schemas.IntSchema
            ):
                pass
            
            
            class props(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    required = {
                        "immutable",
                        "inherited",
                        "mutable",
                    }
                    
                    class properties:
                        immutable = schemas.DictSchema
                        mutable = schemas.DictSchema
                        inherited = schemas.DictSchema
                        __annotations__ = {
                            "immutable": immutable,
                            "mutable": mutable,
                            "inherited": inherited,
                        }
                
                immutable: MetaOapg.properties.immutable
                inherited: MetaOapg.properties.inherited
                mutable: MetaOapg.properties.mutable
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["immutable"]) -> MetaOapg.properties.immutable: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["mutable"]) -> MetaOapg.properties.mutable: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["inherited"]) -> MetaOapg.properties.inherited: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["immutable", "mutable", "inherited", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["immutable"]) -> MetaOapg.properties.immutable: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["mutable"]) -> MetaOapg.properties.mutable: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["inherited"]) -> MetaOapg.properties.inherited: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["immutable", "mutable", "inherited", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    immutable: typing.Union[MetaOapg.properties.immutable, dict, frozendict.frozendict, ],
                    inherited: typing.Union[MetaOapg.properties.inherited, dict, frozendict.frozendict, ],
                    mutable: typing.Union[MetaOapg.properties.mutable, dict, frozendict.frozendict, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'props':
                    return super().__new__(
                        cls,
                        *_args,
                        immutable=immutable,
                        inherited=inherited,
                        mutable=mutable,
                        _configuration=_configuration,
                        **kwargs,
                    )
            name = schemas.StrSchema
            owner = schemas.StrSchema
            publicMetadata = schemas.DictSchema
            __annotations__ = {
                "gameId": gameId,
                "templateId": templateId,
                "id": id,
                "flags": flags,
                "props": props,
                "name": name,
                "owner": owner,
                "publicMetadata": publicMetadata,
            }
    
    gameId: MetaOapg.properties.gameId
    flags: MetaOapg.properties.flags
    id: MetaOapg.properties.id
    templateId: MetaOapg.properties.templateId
    props: MetaOapg.properties.props
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gameId"]) -> MetaOapg.properties.gameId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["templateId"]) -> MetaOapg.properties.templateId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["flags"]) -> MetaOapg.properties.flags: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["props"]) -> MetaOapg.properties.props: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["owner"]) -> MetaOapg.properties.owner: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["publicMetadata"]) -> MetaOapg.properties.publicMetadata: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["gameId", "templateId", "id", "flags", "props", "name", "owner", "publicMetadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gameId"]) -> MetaOapg.properties.gameId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["templateId"]) -> MetaOapg.properties.templateId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["flags"]) -> MetaOapg.properties.flags: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["props"]) -> MetaOapg.properties.props: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["owner"]) -> typing.Union[MetaOapg.properties.owner, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["publicMetadata"]) -> typing.Union[MetaOapg.properties.publicMetadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["gameId", "templateId", "id", "flags", "props", "name", "owner", "publicMetadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        gameId: typing.Union[MetaOapg.properties.gameId, decimal.Decimal, int, ],
        flags: typing.Union[MetaOapg.properties.flags, decimal.Decimal, int, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, ],
        templateId: typing.Union[MetaOapg.properties.templateId, decimal.Decimal, int, ],
        props: typing.Union[MetaOapg.properties.props, dict, frozendict.frozendict, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        owner: typing.Union[MetaOapg.properties.owner, str, schemas.Unset] = schemas.unset,
        publicMetadata: typing.Union[MetaOapg.properties.publicMetadata, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SDTokenGetResponse':
        return super().__new__(
            cls,
            *_args,
            gameId=gameId,
            flags=flags,
            id=id,
            templateId=templateId,
            props=props,
            name=name,
            owner=owner,
            publicMetadata=publicMetadata,
            _configuration=_configuration,
            **kwargs,
        )
