# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from stardust_core_sdk.paths.order_buy.post import OrderBuyPost
from stardust_core_sdk.paths.order_cancel.delete import OrderCancelDelete
from stardust_core_sdk.paths.order_create.post import OrderCreatePost
from stardust_core_sdk.paths.order_get_all.get import OrderGetAllGet
from stardust_core_sdk.paths.order_get.get import OrderGetGet


class OrderEndpointsApi(
    OrderBuyPost,
    OrderCancelDelete,
    OrderCreatePost,
    OrderGetAllGet,
    OrderGetGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
