# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from stardust_core_sdk.paths.player_count.get import PlayerCountGet
from stardust_core_sdk.paths.player_create.post import PlayerCreatePost
from stardust_core_sdk.paths.player_get_all.get import PlayerGetAllGet
from stardust_core_sdk.paths.player_get.get import PlayerGetGet
from stardust_core_sdk.paths.player_get_id.get import PlayerGetIdGet
from stardust_core_sdk.paths.player_get_ids.get import PlayerGetIdsGet
from stardust_core_sdk.paths.player_get_inventory.get import PlayerGetInventoryGet
from stardust_core_sdk.paths.player_mutate.put import PlayerMutatePut
from stardust_core_sdk.paths.player_remove.delete import PlayerRemoveDelete
from stardust_core_sdk.paths.player_wallet_get.get import PlayerWalletGetGet
from stardust_core_sdk.paths.player_withdraw.post import PlayerWithdrawPost


class PlayerEndpointsApi(
    PlayerCountGet,
    PlayerCreatePost,
    PlayerGetAllGet,
    PlayerGetGet,
    PlayerGetIdGet,
    PlayerGetIdsGet,
    PlayerGetInventoryGet,
    PlayerMutatePut,
    PlayerRemoveDelete,
    PlayerWalletGetGet,
    PlayerWithdrawPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
