# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from stardust_core_sdk.paths.template_count.get import TemplateCountGet
from stardust_core_sdk.paths.template_create.post import TemplateCreatePost
from stardust_core_sdk.paths.template_get_all.get import TemplateGetAllGet
from stardust_core_sdk.paths.template_get.get import TemplateGetGet
from stardust_core_sdk.paths.template_get_tokens.get import TemplateGetTokensGet
from stardust_core_sdk.paths.template_mutate.put import TemplateMutatePut
from stardust_core_sdk.paths.template_props_remove.delete import TemplatePropsRemoveDelete
from stardust_core_sdk.paths.template_remove.delete import TemplateRemoveDelete


class TemplateEndpointsApi(
    TemplateCountGet,
    TemplateCreatePost,
    TemplateGetAllGet,
    TemplateGetGet,
    TemplateGetTokensGet,
    TemplateMutatePut,
    TemplatePropsRemoveDelete,
    TemplateRemoveDelete,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
