# coding: utf-8

"""
    Stardust API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2023-05-08T04:33:59Z
    Generated by: https://openapi-generator.tech
"""

from stardust_core_sdk.paths.token_burn.post import TokenBurnPost
from stardust_core_sdk.paths.token_get.get import TokenGetGet
from stardust_core_sdk.paths.token_mint_bulk.post import TokenMintBulkPost
from stardust_core_sdk.paths.token_mutate.put import TokenMutatePut
from stardust_core_sdk.paths.token_props_remove.delete import TokenPropsRemoveDelete
from stardust_core_sdk.paths.token_transfer.post import TokenTransferPost
from stardust_core_sdk.paths.token_withdraw.post import TokenWithdrawPost


class TokenEndpointsApi(
    TokenBurnPost,
    TokenGetGet,
    TokenMintBulkPost,
    TokenMutatePut,
    TokenPropsRemoveDelete,
    TokenTransferPost,
    TokenWithdrawPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
